---
- hosts: all
  become: true

  tasks:

    - name: install software
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - lldpd
        - redis-server
        - python3-pip
        - bash-completion
        - vim
        - tmux

    - name: bring up eth1
      command: ip link set up dev eth1
    
    - name: Install redis-python
      command: pip3 install redis

    - name: Setup network
      command: "{{ item }}"
      ignore_errors: yes
      no_log: true
      with_items:
        - ip link set up dev eth1
        - ip addr add 192.168.1.247/22 dev eth1
        - ip route add 192.168.1.0/24 via 192.168.1.254
        - ip route add 192.168.2.0/24 via 192.168.1.254
        - ip route add 192.168.252.0/24 via 192.168.1.254
        - ip route add 192.168.253.0/24 via 192.168.1.254

    - name: Set redis listening address
      lineinfile:
        name: /etc/redis/redis.conf
        regexp: "^bind *"
        line: "bind 0.0.0.0"

    - name: Restart redis
      command: service redis restart

