---
- hosts: localhost
  become: true

  tasks:

    - file: path=dev/deter state=directory
    - git: 
        repo: "{{item.repo}}" 
        dest: "{{item.dest}}" 
        version: "{{item.version}}"
        accept_hostkey: True 
        key_file: "{{git_key}}"
      with_items:
        - { repo: 'git@github.com:deter-project/testbed.git',   
            dest: '/space/deter/testbed',
            version: 'hotfix' }
        - { repo: 'git@github.com:deter-project/deterboot.git', 
            dest: '/space/deter/deterboot',
            version: 'master' }
        - { repo: 'git@github.com:deter-project/linux-mfs.git', 
            dest: '/space/deter/linux-mfs',
            version: 'master' }
        - { repo: 'git@github.com:deter-project/switch-drivers.git', 
            dest: '/space/deter/switch-drivers',
            version: 'master' }
        - { repo: 'git@github.com:rcgoodfellow/walrustf.git', 
            dest: '/space/walrustf',
            version: 'master' }

    - command: chmod g+w -R /space

